[package]
name = "mytraits"
version = "0.1.0"
edition = "2018"
description = "This crate adds various methods to common typs in order to make your life easier with daily Rust tasks."
license = "MIT"
authors = ["Yang Shuai <yangshuai@gmail.com>"]


[dependencies]
eyre = "0.6.5"
regex = "1.5.4"
